name: Build and Release

on:
  push:
    branches:
      - main  # Trigger on changes to main branch
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    env:
      CI: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/-2'
    - run: npm install
    - run: make public
    - run: NODE_ENV=production npm run build
      
    - name: Create release archive
      run: |
        # Create a zip file with the public folder contents
        cd public
        zip -r ../openscad-playground-release.zip .
        cd ..
        
    - name: Get version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          VERSION="dev-$(date +%Y%m%d-%H%M%S)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: OpenSCAD Playground ${{ steps.get_version.outputs.version }}
        body: |
          OpenSCAD Playground Release ${{ steps.get_version.outputs.version }}
          
          This release contains the built OpenSCAD Playground application ready for deployment.
          
          ## Live Demo
          🌐 **[View Live Demo](https://${{ github.repository_owner }}.github.io/openscad-playground)**
          
          ## Download
          Download the `openscad-playground-release.zip` file below for self-hosting.
        files: openscad-playground-release.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-release
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriat
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4